spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/word_generator_v2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #      ddl-auto: update
      ddl-auto: validate
    show-sql: true